### ISSUE TITLE
BUG: Form Allignment is bad

### ISSUE THREAD

**Issue by harshbhar0629** [BharatSeva/BharatSeva-Plus-HealthCare-Interface#1]
Login form is not align properly.

![form](https://github.com/user-attachments/assets/f4eb836b-113a-4e83-a7e3-3597fe31eb0d)

Please assign to me this issue under gssoc-ext and hacktoberfest-accepted with level-2:)

**Comment by ChetanSingh14** [comment]
can i take this issue?
