### ISSUE TITLE
Issue: Fix ESLint errors in project

### ISSUE THREAD

**Issue by vaibhavyadav-dev** [BharatSeva/BharatSeva-Plus-HealthCare-Interface#3]
The project build is currently failing due to several ESLint errors and warnings during the CI/CD process.  
## To Reproduce:
- Run the build process using:
    ```
    npm run build
    ```
- Observe the build fails due to the above issues.

## Acceptance Criteria:
- The build process runs successfully without any ESLint errors or warnings.
- Unused variables are removed or utilized in the code.
- Missing dependencies are addressed in useEffect hooks.

**Comment by Shivansh-22866** [comment]
@vaibhavyadav-dev  assign this issue to me

**Comment by isha-dubey** [comment]
Hey @vaibhavyadav-dev  , can you please assign this issue to me under hacktoberfest

**Comment by vaibhavyadav-dev** [comment]
> @vaibhavyadav-dev assign this issue to me

ok @Shivansh-22866 go ahead, fix all the warnings, add comments to codes you change, and make sure you've read the contributing guidelines.

**Comment by vaibhavyadav-dev** [comment]
> Hey @vaibhavyadav-dev , can you please assign this issue to me under hacktoberfest

Hey @isha-dubey you can look for other issues or create a new one, there still lot to improve in the existing codebase.
