### ISSUE TITLE
[Feature Request]: Add Password Visibility Toggle to Login and Registration Pages

### ISSUE THREAD

**Issue by MuhammadAshraf23** [BharatSeva/BharatSeva-Plus-HealthCare-Interface#8]
### Description
Implement a password visibility toggle (eye icon) for the password input fields on both the login and registration pages. This feature will allow users to toggle the visibility of the password, making it easier to confirm their input.

### Motivation
Currently, the password fields mask the input by default. Adding a visibility toggle will:

Improve user experience by providing an option to check the entered password.
Reduce the likelihood of login and registration errors due to mistyped passwords.
Ensure consistency across all forms where passwords are entered.
### Expected Behavior
An eye icon (or similar) is displayed within the password input fields on both the login and registration pages.
When the icon is clicked, the password is shown in plain text.
When the icon is clicked again, the password returns to being masked.
The icon changes visually to indicate whether the password is currently visible or hidden.

### please assign me this issue

**Comment by KhushiParekh** [comment]
Hey! Can Solve this issue. Please assign me this issue

**Comment by kshitijhadke26** [comment]
Please assign this issue to me as I have already started resolving this issue.

**Comment by bansalmohit123** [comment]
Hey! Can you please assign me this issue
